gems:
  - jekyll-github-metadata

theme: jekyll-theme-cayman
repository: agimpel/exsi_tipps
title: LaTeX- und Chemdraw-Tipps des Exsikkators
description: Sammlungg für die LaTeX- und Chemdraw-Tipps des Exsikkators, der Fachvereinszeitschrift der Vereinigung der Chemiestudierenden der ETH Zürich.
